import os
import random
import math
import subprocess

def calcular_distancia(x1, y1, z1, x2, y2, z2):
    return math.sqrt((x2 - x1)**2 + (y2 - y1)**2 + (z2 - z1)**2)

def generar_poblacion_xyz(num_archivos, tipos_atomos, carpeta_destino='.'):
    # Crear la carpeta de destino si no existe
    if not os.path.exists(carpeta_destino):
        os.makedirs(carpeta_destino)

    # Pedir al usuario los rangos de coordenadas
    x_min = float(input('Valor mínimo de x: '))
    x_max = float(input('Valor máximo de x: '))
    y_min = float(input('Valor mínimo de y: '))
    y_max = float(input('Valor máximo de y: '))
    z_min = float(input('Valor mínimo de z: '))
    z_max = float(input('Valor máximo de z: '))

    # Pedir al usuario la distancia mínima entre átomos
    distancia_minima = float(input('Distancia mínima entre átomos: '))

    # Pedir al usuario el número total de átomos de cada tipo
    cantidades_atomos = {}
    for tipo_atomo in tipos_atomos:
        cantidad = int(input(f'Número total de átomos de {tipo_atomo}: '))
        cantidades_atomos[tipo_atomo] = cantidad

    # Pedir al usuario la memoria, el número de procesadores y la línea de comandos para los archivos .gjf
    memoria_gjf = input('Memoria para todos los archivos .gjf, ej. 32Gb: ')
    num_procesadores_gjf = input('Número de procesadores para todos los archivos .gjf: ')
    linea_comandos_gjf = input('Línea de comandos para todos los archivos .gjf: ')

    # Pedir al usuario la carga y la multiplicidad una vez
    carga = input('Introduzca la carga para todos los archivos: ')
    multiplicidad = input('Introduzca la multiplicidad para todos los archivos: ')

    # Pedir al usuario ingresar las líneas adicionales una vez
    print("Ingrese las líneas adicionales que desea agregar al final de cada archivo .gjf.")
    print("Presione Enter después de cada línea. Para finalizar, presione Enter dos veces consecutivas.")
    lineas_adicionales = []
    while True:
        linea_adicional = input()
        if not linea_adicional:
            # Verificar si hay un doble salto de línea para finalizar la entrada
            if lineas_adicionales and not lineas_adicionales[-1].strip():
                break
        lineas_adicionales.append(f'{linea_adicional}\n')

    for i in range(num_archivos):
        lineas_originales = []

        # Crear la línea de encabezado
        lineas_originales.append('Generated by XYZ Generator\n')

        # Generar líneas para átomos con coordenadas aleatorias en los rangos proporcionados
        for tipo_atomo, cantidad_atomo in cantidades_atomos.items():
            for _ in range(cantidad_atomo):
                while True:
                    x = random.uniform(x_min, x_max)
                    y = random.uniform(y_min, y_max)
                    z = random.uniform(z_min, z_max)

                    # Verificar la distancia mínima con respecto a los átomos ya generados
                    distancia_valida = all(
                        calcular_distancia(x, y, z, *map(float, partes[1:4])) >= distancia_minima
                        for linea in lineas_originales[1:]
                        for partes in [linea.split()]
                    )

                    if distancia_valida:
                        break

                lineas_originales.append(f'{tipo_atomo} {x:.6f} {y:.6f} {z:.6f}\n')

        # Generar el nombre del archivo .xyz automáticamente
        nombre_archivo_xyz = os.path.join(carpeta_destino, f'archivo_{i + 1}.xyz')

        # Actualizar la línea de encabezado con el número total de átomos
        lineas_originales[0] = f'{len(lineas_originales) - 1}\n'

        # Generar el archivo .gjf a partir del archivo .xyz
        nombre_archivo_gjf = os.path.splitext(nombre_archivo_xyz)[0] + '.gjf'
        with open(nombre_archivo_gjf, 'w') as f_gjf:
            # Escribir la sección de encabezado del archivo .gjf
            f_gjf.write(f'%chk={os.path.basename(nombre_archivo_gjf).replace(".gjf", ".chk")}\n')
            f_gjf.write(f'%mem={memoria_gjf}\n')
            f_gjf.write(f'%nproc={num_procesadores_gjf}\n')
            f_gjf.write(linea_comandos_gjf + '\n\n')

            # Escribir la información adicional utilizando la carga y la multiplicidad introducidas
            nombre_archivo_base = os.path.basename(nombre_archivo_xyz)
            f_gjf.write(f'{nombre_archivo_base}\n')
            f_gjf.write('\n')  # Agregar espacio después del nombre del archivo .xyz
            f_gjf.write(f'{carga} {multiplicidad}\n')

            # Escribir las coordenadas de los átomos en el archivo .gjf
            for idx, linea in enumerate(lineas_originales[1:], start=1):
                f_gjf.write(linea)

            # Agregar una línea en blanco entre las coordenadas y la primera línea añadida por el usuario
            f_gjf.write('\n')

            # Escribir las líneas adicionales al final del archivo .gjf
            f_gjf.writelines(lineas_adicionales)

        print(f'Se ha generado el archivo modificado en {nombre_archivo_gjf}.')

    print("Proceso completado.")

if __name__ == "__main__":
    num_archivos_generar = int(input('Número de archivos a generar: '))
    tipos_atomos = input('Tipos de átomos (separados por espacios, por ejemplo, "H C O"): ').split()

    carpeta_destino = input('Ruta y nombre de la carpeta de destino (por ejemplo, "resultados/"): ')

    generar_poblacion_xyz(num_archivos_generar, tipos_atomos, carpeta_destino)

# Directorio que contiene archivos .gjf
input_directory = carpeta_destino
os.chdir(input_directory)

version_gaussian = "g16"

for file in os.listdir(input_directory):
    
    if os.path.isfile(os.path.join(input_directory, file)):
        #Obtener el nombre del archivo sin extensión
        filename_no_ext = os.path.splitext(file)[0]

        # Ejecutar cálculo Gaussian y obtener la energía
        input_file = os.path.join(input_directory, file)
        output_file = os.path.join(input_directory, f"{filename_no_ext}.log")
        
        comando = f"{version_gaussian} < {filename_no_ext}.gjf > {filename_no_ext}.log &"
        
        try:
            resultado = subprocess.run(comando, shell=True, check=True)
            print(comando)
        except subprocess.CalledProcessError as e:
            print(f"Error al ejecutar el comando para {filename_no_ext}. Código de salida: {e.returncode}")
            print("Error:", e.stderr.decode('utf-8'))